"""Rev A power tables for Gate C: printed as markdown to ../out/budget.md.

Every number carries its source: [DS] vendor datasheet, [WEB] vendor product page,
[CALC] computed here, [ALLOW] an allowance where the maximum is UNKNOWN, [TEST] to measure.
"""
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'out', 'budget.md')
U = None  # UNKNOWN

# ------------------------------------------------------------------ path resistances (ohm)
R_HS_TYP, R_HS_MAX = 0.43, 0.60     # TPS62840 high side at VIN 3.6 V [DS p8]; not specified lower
R_L_TYP, R_L_MAX = 0.116, 0.139     # DFE201612E-2R2M DCR typ [DS Table 2]; max = typ +20 % [ALLOW]
R_LINK = 0.05                       # 0603 0 ohm jumper, max [DS generic]
RON_BAT_TYP, RON_BAT_MAX = 0.115, 0.14  # BQ25185 BAT-SYS [DS p7]

# ------------------------------------------------------------------ CORE_3V3 loads, mA
# (item, typ active, peak, source)
CORE = [
    ('ESP32-S3 (RX / TX peak, 8.5 dBm cap not credited)', 95, 355, '[DS] S3 datasheet RF current'),
    ('GC9A01 panel logic (VCI)', 5, 10, '[ALLOW] panel current table UNKNOWN'),
    ('TLV9061 backlight op-amp', 0.54, 0.75, '[DS] TLV9061 IQ'),
    ('ICM-42670-P 6-axis low-noise', 0.55, 0.55, '[DS] Table 1'),
    ('DRV2605L + LRA (playing)', 0.5, 150, '[ALLOW] LRA not chosen; idle 0.5 mA [DS]'),
    ('TSOP75438 IR receiver', 0.35, 0.45, '[DS] 82494'),
    ('I2C pull-ups (2 x 4.7 k, both low)', 0, 1.4, '[CALC]'),
    ('STAT pull-ups (2 x 10 k, charging)', 0, 0.66, '[CALC]'),
    ('ENC/IMU pulls, switches, misc', 0.05, 0.2, '[CALC]'),
]
S3_SUPPLY_RULE = 500  # MINI-1 v1.7 Table 6-2: the supply must deliver >= 0.5 A

# ------------------------------------------------------------------ SYS loads, mA (peak)
SYS = [
    ('Backlight sink (30 mA full)', 15, 30, '[CALC] Rs 3.3 ohm; LED data UNKNOWN'),
    ('MAX98357A, 8 ohm full scale', 2.4, 260, '[DS] 0.77 W @ 3.7 V 1 % THD; ~85 % eff [ALLOW]'),
    ('SK6805-EC20, full white', 0.5, 60, '[ALLOW] per-LED current UNKNOWN'),
    ('VSMB2943 IR TX pulse (33 R)', 0, 100, '[CALC] (4.6-1.35)/33'),
]


def dropout(v_in, i, r):
    return v_in - i * r


def md_table(head, rows):
    out = '| ' + ' | '.join(head) + ' |\n|' + '---|' * len(head) + '\n'
    for r in rows:
        out += '| ' + ' | '.join('UNKNOWN' if c is None else (f'{c:.3g}' if isinstance(c, float) else str(c))
                                 for c in r) + ' |\n'
    return out


def main():
    md = '# MAO Rev A power tables (generated by schematic/budget.py)\n\n'

    typ3 = sum(r[1] for r in CORE)
    pk3 = sum(r[2] for r in CORE)
    pk3_rule = pk3 - CORE[0][2] + S3_SUPPLY_RULE
    md += '## CORE_3V3 load (mA)\n\n' + md_table(['Load', 'Typ active', 'Peak', 'Source'], CORE)
    md += (f'\n- **Average (typ active):** {typ3:.1f} mA\n'
           f'- **Worst-case simultaneous, datasheet peaks:** {pk3:.1f} mA -> margin {750 - pk3:.0f} mA '
           f'({(750 - pk3) / 750 * 100:.0f} %) under 750 mA\n'
           f'- **Worst case with the S3 at Espressif\'s 500 mA supply rule:** {pk3_rule:.1f} mA -> margin '
           f'{750 - pk3_rule:.0f} mA ({(750 - pk3_rule) / 750 * 100:.0f} %)\n'
           f'- TPS62840 switch current limit 1.0 A min [DS p8]: never reached.\n\n')

    typs = sum(r[1] for r in SYS)
    pks = sum(r[2] for r in SYS)
    md += '## SYS loads besides the regulator (mA)\n\n' + md_table(['Load', 'Typ', 'Peak', 'Source'], SYS)
    i_sys_pk = pks + pk3  # 100 % mode near the floor: regulator input current = output current
    md += (f'\n- **Worst-case SYS (battery) current at the floor:** {pks:.0f} + {pk3:.0f} (regulator in 100 % mode) '
           f'= **{i_sys_pk:.0f} mA**; with the S3 500 mA rule {pks + pk3_rule:.0f} mA.\n'
           f'- BQ25185 BAT-SYS path 3.125 A [DS], JST PH 2 A/contact: OK. The cell and its protection must '
           f'deliver >= {max(i_sys_pk, pks + pk3_rule) / 1000 * 1.2:.2f} A peak (x1.2).\n\n')

    # CORE_3V3 minimum-voltage audit
    rows = []
    for v in (3.2, 3.1, 3.0):
        rows.append([f'{v:.1f} V', 'OK (3.0-3.6)' if v >= 3.0 else 'NO', 'OK (2.7-3.6)',
                     'OK (VCI 2.7-3.3)', 'OK (1.71-3.6)', 'OK (2.0-5.2), weaker LRA drive',
                     'OK (2.0-5.5)', 'OK (1.8-5.5)', 'OK (1.0-5.5)',
                     f'VIH {0.6 * 3.5:.2f} V at SYS 3.5 V: OK'])
    md += ('## CORE_3V3 minimum-voltage audit\n\n' + md_table(
        ['CORE_3V3', 'ESP32-S3 (incl. USB PHY)', 'Flash (in module)', 'Panel / GC9A01', 'ICM-42670-P',
         'DRV2605L', 'TSOP75438', 'TLV9061', 'TPS22916 x2', 'RGB data from IO33'], rows)
        + '\nMax side: CORE_3V3 3.3 V +/- set-point tolerance, +30 mV entering 100 % mode [DS p15]; the panel\'s '
          'VCI max is 3.3 V [Winstar p3], so at the upper tolerance it is a few % over the operating max '
          '(abs max 4.6 V [GC9A01 Table 43]): waiver, Winstar to confirm.\n\n')

    # floor
    rows = []
    for label, rhs, rl, ronb in (('max R', R_HS_MAX, R_L_MAX, RON_BAT_MAX), ('typ R', R_HS_TYP, R_L_TYP, RON_BAT_TYP)):
        for i3, isys, name in ((pk3, i_sys_pk, 'worst-case event'), (CORE[0][2] + 20, CORE[0][2] + 20 + 45, 'TX burst, no audio/haptics')):
            vin = 3.0 + i3 / 1000 * (rhs + rl + R_LINK)
            vbat = vin + isys / 1000 * (ronb + R_LINK)
            rows.append([label, name, i3, isys, f'{vin:.3f}', f'{vbat:.3f}'])
    md += ('## Low-battery floor (PROVISIONAL, not locked)\n\n'
           'Needed: CORE_3V3 >= 3.0 V at the load. In 100 % mode CORE_3V3 = VIN - I x (R_HS + DCR + LINK_REG); '
           'VIN = VBAT(gauge) - I_SYS x (RON_BAT + LINK_BAT). The cell\'s own resistance is outside this: the '
           'gauge measures VBAT after it.\n\n'
           + md_table(['R set', 'Event', 'I 3V3 (mA)', 'I SYS (mA)', 'VIN_REG min (V)', 'VBAT at gauge min (V)'], rows)
           + '\n- TPS62840 R_HS is specified only at VIN 3.6 V (430/600 mOhm); at 3.1-3.4 V it is higher '
             '[TEST at bring-up].\n\n')

    # deep sleep
    ds3 = [
        ('ESP32-S3, deep sleep, ext0+ext1 (RTC periph on)', 8.0, U, 12.0, '[DS] MINI-1 Table 6-7 (typ only)'),
        ('ICM-42670-P wake-on-motion', 4.4, U, 10.0, '[WEB] TDK product page; not in DS v1.0'),
        ('DRV2605L, EN low', 4.0, 7.0, 7.0, '[DS] SLOS854D 6.5'),
        ('ENC_A 470 k pull (low at half the detents)', 3.5, 7.0, 7.0, '[CALC] provisional value'),
        ('MAX17048 SDA/SCL pull-downs vs 4.7 k pull-ups', 0.4, 0.8, 0.8, '[DS] IPD 0.2/0.4 uA per pin'),
        ('IMU INT open-drain leakage x2', 0.0, 0.2, 0.2, '[DS] 100 nA'),
        ('TPS22916 x2 on CORE_3V3, off', 0.02, 0.2, 0.2, '[DS] SLVSDO5F'),
        ('TPD1E10B06 x3 on encoder lines', 0.03, 0.3, 0.3, '[DS] <= 100 nA at 5 V; typ [ALLOW]'),
        ('ENC_B, ENC_SW, straps, STAT (high-Z), VBUS divider', 0.0, 0.0, 0.0, 'design: 0 on battery'),
    ]
    t3 = sum(r[1] for r in ds3)
    w3 = sum(r[3] for r in ds3)
    v_typ, eta_typ, v_w, eta_w = 3.7, 0.80, 3.6, 0.70
    c_typ = t3 * 3.3 / (v_typ * eta_typ)
    c_w = w3 * 3.3 / (v_w * eta_w)
    dsb = [
        ('CORE_3V3 loads, converted', round(c_typ, 1), None, round(c_w, 1),
         f'[CALC] typ VBAT {v_typ} V eta {eta_typ:.0%}; worst {v_w} V eta {eta_w:.0%}'),
        ('TPS62840 IQ', 0.06, U, 0.12, '[DS] 60 nA; 120 nA in 100 % mode'),
        ('BQ25185, battery only', 4.0, 5.0, 5.0, '[DS] IQ_BAT'),
        ('MAX17048, hibernate', 3.0, 5.0, 5.0, '[DS]'),
        ('MAX98357A shutdown (SYS)', 0.6, 2.0, 2.0, '[DS]'),
        ('Backlight FET + LED leakage (SYS)', 0.01, 1.0, 1.0, '[DS] DMG2302UK IDSS; typ [ALLOW]'),
        ('TPS22916 (AUX_SYS), off', 0.01, 0.1, 0.1, '[DS]'),
        ('PCB / capacitor leakage margin', 1.0, U, 3.0, '[ALLOW]'),
    ]
    tt = sum(r[1] for r in dsb)
    tw = sum(r[3] for r in dsb)
    md += ('## Deep-sleep budget (uA)\n\nCORE_3V3 side:\n\n'
           + md_table(['Item', 'Typ', 'Max (DS)', 'Worst used', 'Source'], ds3)
           + f'\nCORE_3V3 subtotal: **{t3:.1f} typ / {w3:.1f} worst**.\n\nBattery side:\n\n'
           + md_table(['Item', 'Typ', 'Max (DS)', 'Worst used', 'Source'], dsb)
           + f'\n**Total: {tt:.1f} uA typical** (target <= 35 uA), **{tw:.1f} uA worst stack** '
             f'(hard limit <= 50 uA applies to the measured board). The worst stack puts every maximum, the '
             f'allowances for the S3 and IMU (no published maximum) and 70 % light-load efficiency together; '
             f'even with the S3 and IMU at typical it is ~{tw - (12 - 8 + 10 - 4.4) * 3.3 / (v_w * eta_w):.0f} uA. '
             f'It is where the risk sits, not an expected value.\n')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf8') as f:
        f.write(md)
    print(md)


if __name__ == '__main__':
    main()
