# Adapted from b5463/kino-d4 hardware/pcb/kino-d4-carrier-a0/design/fab_a02.py @ 68aba75 (ODD JOBS PCB toolchain).
"""Manufacturing package for MAO_MAIN A0 (KiCad 10 python + kicad-cli). Run after the final DRC.

Writes hardware/mao/outputs/fab/:
  gerbers/                F.Cu, In1.Cu-In4.Cu, B.Cu, paste, silk (mask subtracted), mask, Edge.Cuts, Gerber X2,
                          plus the .gbrjob (6 layers, 1.6 mm, JLC06161H-3313)
  drill/                  Excellon, plated and non-plated holes separate, Gerber X2 drill maps
  MAO_MAIN_A0-gerbers.zip gerbers/ and drill/ together, for upload
  CPL-MAO_MAIN_A0.csv     KiCad placement, both sides, mm, DNP and board-only items left out
  CPL-MAO_MAIN_A0-JLC.csv the same rows under JLC's column names (Designator, Mid X, Mid Y, Layer, Rotation)
  BOM-MAO_MAIN_A0-JLC.csv one line per (LCSC, footprint): Comment (the value, or the MPN where one part serves
                          several functions, e.g. the four springs), Designator, Footprint, LCSC Part #,
                          Manufacturer Part, Manufacturer; DNP and excluded-from-BOM parts left out
  ASSEMBLY-MAO_MAIN_A0-top.pdf / -bottom.pdf
                          assembly drawing at 2.5:1: Fab outlines, sketched pads, every reference (mao_labels.py puts
                          one on Fab for each part), DNP crossed out; bottom mirrored as seen from below
  FAB-NOTES.txt           order options and assembly notes that travel with the files (ODD JOBS 178)
The board file is read, never saved. Every BOM line must carry an LCSC number (asserted).
"""
import csv
import os
import shutil
import subprocess
import sys
import zipfile
from collections import OrderedDict
from pathlib import Path

import pcbnew as pcb
from board import TARGET
from netrules import OUTPUTS, NAME

CLI = Path(os.path.expanduser('~/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli'))
OUT = OUTPUTS / 'fab'
LAYERS = 'F.Cu,In1.Cu,In2.Cu,In3.Cu,In4.Cu,B.Cu,F.Paste,B.Paste,F.SilkS,B.SilkS,F.Mask,B.Mask,Edge.Cuts'

NOTES = """MAO_MAIN A0 - fabrication and assembly notes (generated by hardware/mao/design/fab.py)
Review: docs/hardware/mao-rev-a0-review.md     Bring-up: docs/hardware/mao-bringup.md

BOARD
- 6 layers, FR-4 TG155, 1.6 mm, JLCPCB standard 6-layer stackup (JLC06161H-3313). Round, 58.0 mm
  diameter, with a 24 x 6.3 mm notch at 6 o'clock (antenna). Layer order: L1 F.Cu (signals, parts),
  L2 In1.Cu (solid GND), L3 In2.Cu (signals + GND fill), L4 In3.Cu (+3V3 plane), L5 In4.Cu (solid GND),
  L6 B.Cu (signals, parts).
- Copper 1 oz outer, 0.5 oz inner (default). No impedance control ordered: USB 2.0 full speed only.
- ENIG. Black solder mask, white silkscreen (visible product board, ODD JOBS 172). Green is acceptable
  for the 5-unit EVT build if black costs schedule: inspection is easier on green (ODD JOBS 173).
- Through vias only (no blind/buried): {n_std} x 0.3 mm drill / 0.6 mm pad (plane and power vias) and
  {n_fan} x 0.2 / 0.5 mm (designed fan-out beside fine-pitch parts and the module pin rows), all tented both
  sides. {n_th} x 0.2 mm thermal vias inside the U102 / U202 / U501 exposed pads and the module ground pad.
  Via-in-pad: choose epoxy-filled and capped (POFV) if JLC offers it for this 6-layer order; otherwise
  tented / unplugged is acceptable for A0. Min track 0.15 mm, min clearance 0.15 mm: JLC standard
  6-layer capability.
- Milled outline incl. the antenna notch with 1.0 mm inner radii. No V-score. If panelised, place the tabs
  at 3 and 9 o'clock, clear of USB-C (12 o'clock) and the antenna notch (6 o'clock).
- Remove order number, or place it in the S/N box on the back (marked "S/N").

ASSEMBLY (JLC PCBA, both sides)
- Top (F.Cu) first: display support, IMU, face switch, window sensors, Hall sensors, ESD. Then bottom
  (B.Cu): module, power, audio, haptics, USB-C, battery connector.
- USB-C J101 has 4 through-hole shell legs: hand-solder or select THT assembly.
- Footprints without a part: test pads TP1-TP16, Tag-Connect J201 (cable footprint), touch electrodes
  E301/E302 (copper arcs). Springs J302, J303, J501, J502 (BW0019BG, SMT) ARE fitted. LRA (J503) is wired
  by hand after assembly. Display FPC (J301) is a solder land: the panel is hand-soldered (or hot-bar)
  after assembly.
- DNP: R110 (battery NTC substitute, fit only for a 2-wire cell).
- Fiducials: FID1-3 front, FID4-6 back (1 mm copper, 2 mm mask opening).
- Assembly drawing: ASSEMBLY-MAO_MAIN_A0-top.pdf / -bottom.pdf (every reference; resistors and capacitors
  are identified there only, the silkscreen carries ICs, connectors, transistors, diodes and test names).
- Placement file: KiCad rotations. Check every polarised part and pin 1 in JLC's preview, bottom side
  mirrored: SOT-23 (Q101, Q301, Q501), SOT-23-6 (U105), SOT-553 (U101), VQFN/TQFN/TDFN/VSON (U102, U103,
  U104, U202, U501), LGA (U401), DFN (U403), VL53L4CD (U402), SPH0641 (MK401), DRV5012 (U301, U302),
  diodes (D101, D301-D304), LEDs (D501, D502), JST SH (J102), USB-C (J101), module (U201).
- X-ray if offered: U102, U104, U202, U501 (exposed pads), U401 (LGA), U201.
"""


def cli(*args):
    r = subprocess.run([str(CLI), *map(str, args)], capture_output=True, text=True)
    assert r.returncode == 0, (args, r.stdout, r.stderr)


def field(f, name):
    for fl in f.GetFields():
        if fl.GetName() == name:
            return fl.GetText()
    return ''


def main():
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / 'gerbers').mkdir(parents=True)
    (OUT / 'drill').mkdir()
    cli('pcb', 'export', 'gerbers', '--layers', LAYERS, '--subtract-soldermask', '-o', OUT / 'gerbers', TARGET)
    cli('pcb', 'export', 'drill', '--format', 'excellon', '--excellon-separate-th', '--generate-map',
        '--map-format', 'gerberx2', '-u', 'mm', '-o', OUT / 'drill', TARGET)
    for side, layers, extra in (('top', 'F.Fab,Edge.Cuts', []), ('bottom', 'B.Fab,Edge.Cuts', ['--mirror'])):
        cli('pcb', 'export', 'pdf', '--mode-single', '--layers', layers, *extra, '--sketch-pads-on-fab-layers',
            '--crossout-DNP-footprints-on-fab-layers', '--include-border-title', '--black-and-white', '--scale', '2.5',
            '-o', OUT / ('ASSEMBLY-%s-%s.pdf' % (NAME, side)), TARGET)
    cpl = OUT / ('CPL-%s.csv' % NAME)
    cli('pcb', 'export', 'pos', '--side', 'both', '--format', 'csv', '--units', 'mm', '--exclude-dnp', '-o', cpl, TARGET)

    b = pcb.LoadBoard(str(TARGET))
    fps = {f.GetReference(): f for f in b.GetFootprints()}
    skip = {r for r, f in fps.items() if f.IsExcludedFromBOM() or f.IsBoardOnly() or f.IsDNP()
            or r.startswith(('FID', 'TP', 'H'))}
    rows = [r for r in csv.DictReader(open(cpl)) if r['Ref'] not in skip]
    with open(cpl, 'w', newline='') as fh:
        w = csv.DictWriter(fh, fieldnames=['Ref', 'Val', 'Package', 'PosX', 'PosY', 'Rot', 'Side'])
        w.writeheader()
        w.writerows(rows)
    with open(OUT / ('CPL-%s-JLC.csv' % NAME), 'w', newline='') as fh:
        w = csv.writer(fh)
        w.writerow(['Designator', 'Mid X', 'Mid Y', 'Layer', 'Rotation'])
        for r in rows:
            w.writerow([r['Ref'], r['PosX'] + 'mm', r['PosY'] + 'mm', 'Top' if r['Side'] == 'top' else 'Bottom', r['Rot']])
    with zipfile.ZipFile(OUT / ('%s-gerbers.zip' % NAME), 'w', zipfile.ZIP_DEFLATED) as z:
        for p in sorted((OUT / 'gerbers').iterdir()) + sorted((OUT / 'drill').iterdir()):
            z.write(p, p.name)

    lines = OrderedDict()
    for ref in sorted(fps, key=lambda r: (''.join(c for c in r if c.isalpha()), int(''.join(c for c in r if c.isdigit()) or 0))):
        f = fps[ref]
        if ref in skip:
            continue
        lcsc = field(f, 'LCSC')
        assert lcsc, ('BOM part without an LCSC number', ref)
        key = (lcsc, str(f.GetFPID().GetLibItemName()))
        line = lines.setdefault(key, {'refs': [], 'values': [], 'mpn': field(f, 'MPN'), 'mfr': field(f, 'Manufacturer')})
        assert line['mpn'] == field(f, 'MPN'), ('one LCSC number, two MPNs', ref)
        line['refs'].append(ref)
        line['values'].append(f.GetValue())
    with open(OUT / ('BOM-%s-JLC.csv' % NAME), 'w', newline='') as fh:
        w = csv.writer(fh)
        w.writerow(['Comment', 'Designator', 'Footprint', 'LCSC Part #', 'Manufacturer Part', 'Manufacturer', 'Quantity'])
        for (lcsc, fp), line in lines.items():
            value = line['values'][0] if len(set(line['values'])) == 1 else line['mpn']
            w.writerow([value, ','.join(line['refs']), fp, lcsc, line['mpn'], line['mfr'], len(line['refs'])])
    vias = [t for t in b.GetTracks() if isinstance(t, pcb.PCB_VIA)]
    n_th = sum(1 for f in fps.values() for p in f.Pads()
               if p.GetAttribute() == pcb.PAD_ATTRIB_PTH and p.GetDrillSize().x < pcb.FromMM(0.25))
    (OUT / 'FAB-NOTES.txt').write_text(NOTES.format(
        n_std=sum(1 for v in vias if v.GetDrillValue() >= pcb.FromMM(0.3)),
        n_fan=sum(1 for v in vias if v.GetDrillValue() < pcb.FromMM(0.3)), n_th=n_th))
    n = sum(len(l['refs']) for l in lines.values())
    print('fab: gerbers %d files, drill %d files, BOM %d lines / %d parts, CPL %d rows' % (
        len(list((OUT / 'gerbers').iterdir())), len(list((OUT / 'drill').iterdir())), len(lines), n, len(rows)), flush=True)


if __name__ == '__main__':
    main()
    sys.stdout.flush()
    os._exit(0)
