"""Write the firmware board pin header and the pin-map document from pinmap.py.

    python3 hardware/mao/design/gen_pinmap.py
"""
from pathlib import Path

import pinmap
from netrules import ROOT

REPO = ROOT.parents[1]
HEADER = REPO / 'components/mao_board/boards/main_a0/mao_board_pins.h'
DOC = REPO / 'docs/hardware/mao-pin-map.md'



def flags(gpio):
    f = []
    if gpio in (0, 3, 45, 46):
        f.append('strap')
    if gpio <= 21:
        f.append('RTC')
    if 1 <= gpio <= 14:
        f.append('touch')
    if 1 <= gpio <= 10:
        f.append('ADC1')
    return ', '.join(f)


def header():
    lines = ['/*',
             ' * MAO_MAIN A0 physical assignments. PRIVATE to mao_board.',
             ' * GENERATED by hardware/mao/design/gen_pinmap.py from pinmap.py - do not edit.',
             ' */',
             '#pragma once', '']
    lines.append('/* ESP32-S3 GPIOs */')
    for gpio, net, d, fn, note in pinmap.NATIVE:
        if not net or net in ('USB_DP', 'USB_DN') or net.startswith('UART_'):
            continue                      # USB and console pins belong to the IDF drivers
        lines.append('#define MAO_PIN_%-18s %2d   /* %s */' % (net, gpio, fn))
    lines += ['', '/* TCA6408A expander port bits (I2C 0x20) */']
    for bit, net, d, fn, pull in pinmap.EXPANDER:
        lines.append('#define MAO_EXP_%-18s %d    /* %s; %s */' % (net, bit, fn, pull))
    lines += ['', '/* I2C 7-bit addresses */']
    names = {0x20: 'EXPANDER', 0x29: 'TOF', 0x36: 'FUEL_GAUGE', 0x44: 'ALS', 0x5A: 'HAPTIC', 0x6A: 'IMU'}
    for addr, what in sorted(pinmap.I2C_ADDRESSES.items()):
        lines.append('#define MAO_I2C_ADDR_%-12s 0x%02X /* %s */' % (names[addr], addr, what))
    return '\n'.join(lines) + '\n'


def doc():
    out = ['# MAO_MAIN A0 pin map', '',
           'Generated from `hardware/mao/design/pinmap.py` by `gen_pinmap.py`; the same table drives the',
           'schematic nets and `components/mao_board/boards/main_a0/mao_board_pins.h` (ODD JOBS 199).',
           'Flags: strap = boot strapping pin, RTC = usable in deep sleep (wake/hold), touch = capacitive',
           'channel, ADC1 = ADC usable with Wi-Fi on.', '',
           '## ESP32-S3-WROOM-1-N8R2', '',
           '| GPIO | Net | Dir | Function | Flags | Notes |', '|---:|---|---|---|---|---|']
    for gpio, net, d, fn, note in pinmap.NATIVE:
        out.append('| %d | %s | %s | %s | %s | %s |' % (gpio, '`%s`' % net if net else '—', d, fn, flags(gpio), note))
    used = sum(1 for r in pinmap.NATIVE if r[1])
    spare = [str(r[0]) for r in pinmap.NATIVE if not r[1]]
    out += ['', '%d of %d module signal pins used; spare: GPIO %s.' % (used, len(pinmap.NATIVE), ', '.join(spare)), '',
            '## TCA6408A expander (I2C 0x20)', '',
            'All expander pins are high-Z inputs without pull-ups from power-on until firmware configures them,',
            'so the external resistors below are the hardware defaults (ODD JOBS 116/117).', '',
            '| Port | Net | Dir | Function | Power-on default |', '|---:|---|---|---|---|']
    for bit, net, d, fn, pull in pinmap.EXPANDER:
        out.append('| P%d | `%s` | %s | %s | %s |' % (bit, net, d, fn, pull))
    out += ['', '## I2C address map (one bus, 2.2 kΩ pull-ups, 400 kHz)', '', '| Address | Device |', '|---|---|']
    for addr, what in sorted(pinmap.I2C_ADDRESSES.items()):
        out.append('| 0x%02X | %s |' % (addr, what))
    out += ['', 'No collisions.', '']
    return '\n'.join(out)


if __name__ == '__main__':
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(header())
    DOC.write_text(doc())
    print('wrote', HEADER.relative_to(REPO), 'and', DOC.relative_to(REPO))
