M48
; DRILL file KiCad 10.0.6 date 2026-10-06T21:25:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-06T21:25:36+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.200
%
G90
G05
T1
X47.11Y-26.65
X52.89Y-26.65
T2
X63.384Y-69.14
X64.4Y-64.06
X65.416Y-69.14
T3
X32.322Y-67.678
T4
X31.421Y-33.272
X68.579Y-33.272
M30
