M48
; DRILL file KiCad 10.0.6 date 2026-10-05T01:23:28
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-05T01:23:28+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C2.200
%
G90
G05
T1
X71.36Y-55.324
T2
X47.11Y-26.65
X52.89Y-26.65
T3
X64.184Y-65.06
X65.2Y-70.14
X66.216Y-65.06
T4
X32.322Y-67.678
T5
X31.421Y-33.272
X68.579Y-33.272
M30
