#!/usr/bin/env python3
"""Independent oracle for the ODD link key schedule (docs/link_security.md).

Computes every derived value for fixed inputs with pyca/cryptography
(OpenSSL), checks the standard published vectors, and writes
components/odd_link/odd_link_vectors.h. The firmware self-test
(odl_selftest) must reproduce these bytes with PSA Crypto on the target:
two independent implementations agreeing, not "our encrypt matches our
decrypt".

    python tools/odd_link_vectors.py        # regenerate the header
"""
import hashlib
import hmac
import os
import struct

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey, X25519PublicKey
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

H = bytes.fromhex


def hkdf(salt, ikm, info, n):
    return HKDF(algorithm=hashes.SHA256(), length=n, salt=salt or None, info=info).derive(ikm)


def hm(key, *parts):
    return hmac.new(key, b"".join(parts), hashlib.sha256).digest()


def sha(*parts):
    return hashlib.sha256(b"".join(parts)).digest()


# ---- standard vectors (checked against OpenSSL here, and again on target) ----
STD = {
    "sha256_abc": sha(b"abc"),
    "hmac_4231_1": hm(b"\x0b" * 20, b"Hi There"),
    "hmac_4231_2": hm(b"Jefe", b"what do ya want for nothing?"),
    "hkdf_5869_1": hkdf(H("000102030405060708090a0b0c"), b"\x0b" * 22, H("f0f1f2f3f4f5f6f7f8f9"), 42),
}
assert STD["sha256_abc"].hex() == "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
assert STD["hmac_4231_1"].hex() == "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7"
assert STD["hmac_4231_2"].hex() == "5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843"
assert STD["hkdf_5869_1"].hex() == ("3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf"
                                    "34007208d5b887185865")

# RFC 7748 section 6.1
A_PRIV = H("77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a")
B_PRIV = H("5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb")
a = X25519PrivateKey.from_private_bytes(A_PRIV)
b = X25519PrivateKey.from_private_bytes(B_PRIV)
A_PUB = a.public_key().public_bytes_raw()
B_PUB = b.public_key().public_bytes_raw()
Z = a.exchange(X25519PublicKey.from_public_bytes(B_PUB))
assert A_PUB.hex() == "8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a"
assert B_PUB.hex() == "de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f"
assert Z.hex() == "4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742"
assert Z == b.exchange(X25519PublicKey.from_public_bytes(A_PUB))

# ---- the ODD key schedule for fixed inputs ----
CTRL_ID, DEV_ID = 0x0DD09888E0D4D090, 0x0DD06055F9235324
MAC_C, MAC_D = H("9888e0d4d090"), H("6055f9235324")
TXID = H("0102030405060708")
NONCE_C = bytes(range(0xA0, 0xB0))
NONCE_D = bytes(range(0xB0, 0xC0))
IDS = struct.pack(">QQ", CTRL_ID, DEV_ID)

commit = sha(b"ODD-PAIR-COMMIT-v1", TXID, IDS, A_PUB, B_PUB, NONCE_D)
th = sha(b"ODD-PAIR-TRANSCRIPT-v1", b"\x01", IDS, MAC_C, MAC_D, TXID, A_PUB, B_PUB, NONCE_C, NONCE_D)
k_confirm = hkdf(th, Z, b"ODD-PAIR-CONFIRM-v1", 32)
k_link = hkdf(th, Z, b"ODD-LINK-KEY-v1", 32)
sas = int.from_bytes(hkdf(th, Z, b"ODD-PAIR-SAS-v1", 8), "big") % 1000000
tag_c = hm(k_confirm, b"ODD-PAIR-CONFIRM-C", th)
tag_d = hm(k_confirm, b"ODD-PAIR-CONFIRM-D", th)
k_hello = hkdf(b"", k_link, b"ODD-LINK-HELLO-v1" + IDS, 32)
hello = hm(k_hello, b"H1", IDS, MAC_C, MAC_D, NONCE_C)[:16]
hello_ack = hm(k_hello, b"H2", IDS, MAC_C, MAC_D, NONCE_C, NONCE_D)[:16]
okm = hkdf(NONCE_C + NONCE_D, k_link, b"ODD-LINK-SESSION-v1" + IDS + MAC_C + MAC_D, 88)
lmk, k_c2d, k_d2c, sid = okm[:16], okm[16:48], okm[48:80], okm[80:88]
inner = b"OD" + bytes(range(1, 11))
hdr = b"LK\x01\x20" + sid + struct.pack(">I", 1)
env = hdr + inner + hm(k_c2d, hdr, inner)[:16]
fp = int.from_bytes(sha(b"ODD-KEY-FP-v1", k_link)[:4], "big")

VEC = {
    "std_sha256_abc": STD["sha256_abc"], "std_hmac_1": STD["hmac_4231_1"], "std_hmac_2": STD["hmac_4231_2"],
    "std_hkdf_1": STD["hkdf_5869_1"],
    "x_a_priv": A_PRIV, "x_b_priv": B_PRIV, "x_a_pub": A_PUB, "x_b_pub": B_PUB, "x_shared": Z,
    "commit": commit, "th": th, "k_confirm": k_confirm, "k_link": k_link, "tag_c": tag_c, "tag_d": tag_d,
    "k_hello": k_hello, "hello_tag": hello, "hello_ack_tag": hello_ack,
    "lmk": lmk, "k_c2d": k_c2d, "k_d2c": k_d2c, "sid": sid, "env_inner": inner, "env_frame": env,
}


def carr(name, data):
    body = ", ".join(f"0x{x:02x}" for x in data)
    return f"static const uint8_t kV_{name}[{len(data)}] = {{ {body} }};"


out = ["/* Generated by tools/odd_link_vectors.py (pyca/cryptography " + __import__("cryptography").__version__ +
       ", OpenSSL). Do not edit. Expected values for odl_selftest(). */",
       "#pragma once", "#include <stdint.h>", ""]
out += [carr(k, v) for k, v in VEC.items()]
out += ["", f"#define kV_ctrl_id 0x{CTRL_ID:016X}ULL", f"#define kV_dev_id 0x{DEV_ID:016X}ULL",
        f"#define kV_sas {sas}u", f"#define kV_fp 0x{fp:08X}u", carr("mac_c", MAC_C), carr("mac_d", MAC_D),
        carr("txid", TXID), carr("nonce_c", NONCE_C), carr("nonce_d", NONCE_D), ""]
path = os.path.join(os.path.dirname(__file__), "..", "components", "odd_link", "odd_link_vectors.h")
open(path, "w", newline="\n").write("\n".join(out))
print(f"wrote {os.path.normpath(path)}: sas {sas:06d}, key fingerprint {fp:08x}")
