#!/usr/bin/env python3
"""The ODD JOBS maker's mark for MAO: the symbol only, from the official artwork.

    python tools/odd_jobs_mark.py "C:/Users/.../ODD JOBS/oddjobs.png" [--height 64]

Reads the official logo (symbol above the "odd jobs" wordmark, black on
transparent) without modifying it, and writes:

  assets/sprites/odd_jobs_symbol.png          the symbol alone, full resolution,
                                              trimmed, transparent (no wordmark)
  components/mao_ui/mao_mark_odd_jobs.c       an A8 alpha mask at display size -
                                              coverage only, no colour: MAO
                                              tints it with its current accent

The symbol is separated from the wordmark at the widest fully transparent band
of rows between them; nothing is redrawn, only cropped and scaled (with
area-averaged alpha for clean anti-aliased edges).
"""
import argparse
import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def symbol_box(alpha):
    """Bounding box of the symbol: everything above the gap before the wordmark."""
    w, h = alpha.size
    px = alpha.load()
    rows = [any(px[x, y] > 8 for x in range(0, w, 2)) for y in range(h)]
    top = rows.index(True)
    # the transparent bands below the first ink; the widest separates symbol / wordmark
    bands, y = [], top
    while y < h:
        if not rows[y]:
            s = y
            while y < h and not rows[y]:
                y += 1
            if y < h:
                bands.append((y - s, s, y))
        y += 1
    if not bands:
        raise SystemExit("no gap between symbol and wordmark found")
    _, gap_start, _ = max(bands)
    return alpha.crop((0, top, w, gap_start)).getbbox(), top


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("source")
    ap.add_argument("--height", type=int, default=64, help="display height in px (the mark's rows)")
    a = ap.parse_args()
    src = Image.open(a.source).convert("RGBA")
    alpha = src.getchannel("A")
    (x1, y1, x2, y2), top = symbol_box(alpha)
    box = (x1, top + y1, x2, top + y2)
    sym = src.crop(box)
    os.makedirs(os.path.join(ROOT, "assets", "sprites"), exist_ok=True)
    out_png = os.path.join(ROOT, "assets", "sprites", "odd_jobs_symbol.png")
    sym.save(out_png)
    # display mask: height px tall, proportions kept, alpha area-averaged
    h = a.height
    w = max(1, round(sym.width * h / sym.height))
    w += w & 1                                     # even width: it centres on whole pixels
    mask = sym.getchannel("A").resize((w, h), Image.BOX)
    data = list(mask.getdata())
    lines = []
    for r in range(h):
        row = data[r * w:(r + 1) * w]
        lines.append("    " + ", ".join("0x%02x" % v for v in row) + ",")
    c = "\n".join([
        "/*",
        " * The ODD JOBS maker's mark (symbol only - never the wordmark), as an A8",
        " * alpha mask: coverage, no colour; MAO draws it in its current accent.",
        " * Generated by tools/odd_jobs_mark.py from the official artwork",
        " * (%s, %dx%d); symbol %dx%d px, here %dx%d." % (os.path.basename(a.source), src.width, src.height,
                                                        sym.width, sym.height, w, h),
        " * Do not edit by hand.",
        " */",
        "#include \"mao_ui_priv.h\"",
        "",
        "static const uint8_t kMark[%d * %d] = {" % (w, h),
        *lines,
        "};",
        "",
        "const lv_image_dsc_t mao_mark_odd_jobs = {",
        "    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8, .w = %d, .h = %d, .stride = %d }," % (w, h, w),
        "    .data_size = sizeof(kMark),",
        "    .data = kMark,",
        "};",
        ""])
    out_c = os.path.join(ROOT, "components", "mao_ui", "mao_mark_odd_jobs.c")
    with open(out_c, "w", newline="\n") as f:
        f.write(c)
    print("source %dx%d; symbol box %s = %dx%d; mask %dx%d (%d bytes)" % (
        src.width, src.height, box, sym.width, sym.height, w, h, w * h))
    print("wrote", os.path.relpath(out_png, ROOT), "and", os.path.relpath(out_c, ROOT))


if __name__ == "__main__":
    main()
